language: go
sudo: false
addons:
  postgresql: 9.3
go:
  - 1.8
  - 1.9
  - tip
install:
  - go get github.com/urfave/cli
  - go get github.com/lib/pq
  - go get github.com/jmoiron/sqlx
  - go get github.com/tealeg/xlsx
  - go get github.com/lukasmartinelli/pgfutter
  - go get github.com/andrew-d/go-termutil
script:
  - go install
  - ./test.sh
